print('Какое у Вас животное?')
species = input()
print('Кличка Вашего питомца?')
name = input()
print('Возраст Вашего питомца?')
age = input()
print('Это '+species+' по кличке '+name+', которому(ой) '+age+' лет (года)')